### ISSUE TITLE
Unable to add RSA key to DID document

### ISSUE THREAD

**Issue by johnptoohey** [veres-one/did-client-veres-one#4]
Using 0.3.2 of the did client. I can easily generate and add a ECC DID to the testnet and to the dominode.testnet. However, trying to add a RSA key give an error. The local DID document is created correctly, but the error comes when the client attempts to register it to the blockchain.

λ Hypatia-1 did-client → λ git master → ./did generate -t rsa -r -H testnet.veres.one
[Veres One][test] Generating a new Veres One DID...
[Veres One][test] Generating keypair... (5-15 seconds)
[Veres One][test] DID: did:v1:test:nym:z2czTJ1VD9p7WAzFQNrqhrMw7BV3UTUTar7QoV3tQ2gPHEufsmxy
[Veres One][test] Storing DID Document on disk...
[Veres One][test] DID Document stored in: /Users/johntoohey/.testdid/did-v1-test-nym-z2czTJ1VD9p7WAzFQNrqhrMw7BV3UTUTar7QoV3tQ2gPHEufsmxy.jsonld
[Veres One][test] Local DID generation successful.
[Veres One][test] Preparing to register a DID on Veres One...
[Veres One][test] Generating Equihash proof of work... (60-120 seconds)
TypeError: Cannot read property '0' of undefined
    at _send (/Users/johntoohey/Dev/repos/git/v1/did-client/lib/drivers/veres.js:209:47)

**Comment by dmitrizagidulin** [comment]
What was the issue, out of curiosity?
